# Generated by Django 2.2.1 on 2019-06-09 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('mechweb', '0005_auto_20190609_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Awards Home',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='researchlabpage',
            name='lab_research_area',
            field=models.CharField(choices=[('0', 'Other'), ('1', 'Machine Design Engineering'), ('2', 'Manufacturing Engineering'), ('3', 'Thermal and Fluid Engineering')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='alumnuspage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('0', 'Faculty'), ('1', 'Student'), ('2', 'Alumnus'), ('3', 'Staff')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FacultyAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('award_title', models.CharField(max_length=100)),
                ('award_description', wagtail.core.fields.RichTextField(blank=True)),
                ('award_type', models.CharField(choices=[('0', 'Faculty Awarded'), ('1', 'Best Paper'), ('2', 'Other')], default='0', max_length=2)),
                ('award_time', models.DateField()),
                ('conferrer', models.CharField(max_length=100)),
                ('conferrer_description', wagtail.core.fields.RichTextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=250)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fac_award', to='mechweb.FacultyPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
