# Generated by Django 2.2.1 on 2019-06-11 04:25

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0014_mechhomepage_hod_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardhomepage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
