# Generated by Django 2.2.1 on 2019-06-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0020_auto_20190612_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnuspage',
            name='dppc',
            field=models.CharField(choices=[('6', 'Not Applicable'), ('0', 'Chairman'), ('1', 'Secretary'), ('2', 'Faculty Member'), ('3', 'External Member'), ('4', 'PhD Student Member'), ('5', 'MTech Student Member')], default='6', max_length=2),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='eligible_specializations',
            field=models.CharField(choices=[('0', 'Not Applicable'), ('1', 'Aerodynamics & Propulsion'), ('2', 'Manufacturing Science and Engineering'), ('3', 'Computational Mechanics'), ('4', 'Fluids and Thermal'), ('5', 'Machine Design')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='studentpage',
            name='dppc',
            field=models.CharField(choices=[('6', 'Not Applicable'), ('0', 'Chairman'), ('1', 'Secretary'), ('2', 'Faculty Member'), ('3', 'External Member'), ('4', 'PhD Student Member'), ('5', 'MTech Student Member')], default='6', max_length=2),
        ),
    ]
