# Generated by Django 2.2.1 on 2019-06-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0034_customuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultypage',
            name='website',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
