# Generated by Django 2.2.1 on 2019-06-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0037_auto_20190617_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='alt_people_text',
            field=models.CharField(blank=True, help_text="Use this only if you can't add faculty and other authors above", max_length=1000),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='citations',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='page_end',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='page_start',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='pub_vol',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
