# Generated by Django 2.2.1 on 2019-06-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0043_interestcategorieshomepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultypage',
            name='fac_research_categories',
            field=models.ManyToManyField(blank=True, related_name='faculty', to='mechweb.InterestCategories'),
        ),
    ]
