# Generated by Django 2.2.1 on 2019-07-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0056_auto_20190719_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='pub_journal',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
