# Generated by Django 2.2.1 on 2019-07-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0063_auto_20190719_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='eligible_programmes',
            field=models.ManyToManyField(blank=True, related_name='courses', to='mechweb.CourseProgrammes'),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='eligible_specializations',
            field=models.ManyToManyField(blank=True, related_name='courses', to='mechweb.CourseSpecializations'),
        ),
    ]
