# Generated by Django 2.2.1 on 2019-07-19 15:10

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0064_auto_20190719_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='eligible_programmes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='courses', to='mechweb.CourseProgrammes'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='eligible_specializations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='courses', to='mechweb.CourseSpecializations'),
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='fac_research_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='faculty', to='mechweb.Categories'),
        ),
    ]
