u = 'nelsonm'
a = CustomUser.objects.all().get(username=u)
print('Username: ,'a.username)
print('Email: ', a.email)
print('First Name: ', a.first_name)
print('Middle Name: ', a.middle_name)
print('Last Name: ', a.last_name)
print('_Password: ', a._password)
print('Password: ', a.password)
print("------------------------")
print('Superuser: ', a.is_superuser)
print('Staff: ', a.is_staff)
print('Active: ', a.is_active)
print('User_type: ', a.get_user_type_display)
print("------------------------")
print(a.uid)
print(a.has_usable_password())
print(a.last_login)
print(a.date_joined)
print(a.get_full_name())
print(a.get_short_name())
print("------------------------")
a.groups
a.user_permissions
a.get_user_permissions()
a.get_group_permissions()
a.get_all_permissions()
print("------------------------")
a.username_validator # UnicodeUsernameValidator()
a.objects # UserManager()
print("------------------------")
perm = 'wagtailadmin.access_admin'
print(a.has_perm(perm))
