# Generated by Django 3.1.2 on 2022-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reason',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
