# Generated by Django 3.1.1 on 2020-10-17 21:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('team_members', wagtail.core.fields.StreamField([('team_members', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Full name of the team member')), ('email', wagtail.core.blocks.CharBlock(help_text='Email of the team member', required=False)), ('por', wagtail.core.blocks.CharBlock(help_text='Position of responsibility of the team member')), ('linkedin_url', wagtail.core.blocks.URLBlock(help_text='Url of the linkedin profile', required=False)), ('facebook_url', wagtail.core.blocks.URLBlock(help_text='Url of the facebook profile', required=False)), ('profile_picture', wagtail.images.blocks.ImageChooserBlock(help_text='Profile picture of the team member', required=False))]))], blank=True, null=True)),
                ('team_bg_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MesaHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about', models.TextField(blank=True, null=True)),
                ('our_aim', models.TextField(blank=True, null=True)),
                ('scrolling_text', models.TextField(blank=True, null=True)),
                ('gallery_images', wagtail.core.fields.StreamField([('GalleryImages', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True)),
                ('announcement_cards', wagtail.core.fields.StreamField([('announcement_card', wagtail.core.blocks.StructBlock([('info', wagtail.core.blocks.TextBlock(help_text='Add more information about the announcement', required=False)), ('button_link', wagtail.core.blocks.URLBlock(help_text='Add the related url', required=False)), ('button_text', wagtail.core.blocks.CharBlock(help_text='Add text for the button', required=False)), ('button_tooltip', wagtail.core.blocks.CharBlock(help_text='Add text for the tooltip of the button', required=False)), ('last_updated', wagtail.core.blocks.DateTimeBlock(auto_now=True, required=True)), ('card_image', wagtail.images.blocks.ImageChooserBlock(help_text='Add image for the announcement card', required=True)), ('tag', wagtail.core.blocks.ChoiceBlock(choices=[('new', 'New'), ('important', 'Important'), ('outdated', 'outdated')], icon='cup', null=True, required=False))]))], blank=True, null=True)),
                ('about_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('our_aim_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Mesa',
            },
            bases=('wagtailcore.page',),
        ),
    ]
