# Generated by Django 3.1.1 on 2020-10-31 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesahomepage',
            options={},
        ),
    ]
