# Generated by Django 3.1.1 on 2020-10-31 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('mesa', '0003_mesahomepage_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesahomepage',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
