from mechweb.models import AwardHomePage, AwardPage, Award
from django.utils.text import slugify
import string
import random

def transfer():
    not_created = []
    award_home = AwardHomePage.objects.all()[0]
    awards = Award.objects.all()
    for award in awards:
        try:
            res = ''.join(random.choices(string.ascii_uppercase +string.digits, k=5))
            awd = AwardPage(
                title = award.award_title,
                slug = AwardPage()._get_autogenerated_slug(slugify(award.award_title+"_"+award.award_type+"_"+res)),
                faculty_id = award.faculty_id,
                other_recipients = award.other_recipients,
                award_title = award.award_title,
                award_description = award.award_description,
                award_type = award.award_type,
                award_time = award.award_time,
                conferrer = award.conferrer,
                conferrer_description = award.conferrer_description,
                image_id = award.image_id,
                link = award.link,
                alt_recipient_text = award.alt_recipient_text,
            )
            award_home.add_child(instance=awd)
            awd.save()
            award_home.save()
            print(f"Created {award.id}\n")
        except Exception as e:
            not_created.append({"awardID":award.id, "reason":str(e)})
            print(f"Failed to add award. no. {award.id}  due to {str(e)}\n")
    print(not_created)
    return not_created
