import csv
import datetime
from mechweb import wagtail_hooks
from mechweb.models import CustomUser, ResearchLabHomePage, ResearchLabPage

lab_types = (
	('0', 'UG Lab'),
	('1', 'PG Lab'),
)

lab_home = ResearchLabHomePage.objects.all()[0]
lab_number = ResearchLabPage.objects.all().count()
with open('mechweb/automation_scripts/labs.tsv', mode='r') as tsv_file:
    tsv_reader = csv.DictReader(tsv_file, dialect='excel-tab')
    line_count = 0
    logf = open("mechweb/automation_scripts/lab_errors.log", "a")
    logf.write("----------------------------------\nAdding labs on  {0}\n----------------------------------\n".format(datetime.datetime.now() ))
    for row in tsv_reader:
        if line_count == 0:
        	pass
        	#can add to check csv format
        try:
            print("Creating lab: {}".format(str(row["name"])))
            if row["lab_type"]:
            	lt = row["lab_type"]
            else:
            	lt=0
            try:
                current_lab_number=lab_number+line_count
                base_slug = ResearchLabPage()._get_autogenerated_slug(current_lab_number)
            except:
                base_slug = ResearchLabPage()._get_autogenerated_slug(slugify(row["lab_type"]+"_"+row["name"]))
                
            lab=ResearchLabPage(
                title=row["name"],
                slug=base_slug,
                name=row["name"],
                lab_type=lt,
                #------------------------------
                intro=row["intro"],
                body=row["body"],
                contact_number=row["contact_number"],
                address=row["address"],
            )
            lab_home.add_child(instance=lab)
            lab_home.save()
            print("Created!")
        except Exception as e:
            logf.write("{0}\n".format(str(e)))
            # logf.write("Failed to add lab. no. {0} | {1}:{2} due to {3}\n".format(line_count, lab_types[int(row["lab_type"])], str(row["name"]), str(e)))
        line_count += 1
    logf.close()

# # for deleting the labs
# from mechweb.models import ResearchLabPage
# for lab in ResearchLabPage.objects.all():
#     print("Deleting",lab.title)
#     lab.delete()
#     print("Deleted!")

# from mechweb.automation_scripts import create_labs
