# Generated by Django 2.2.1 on 2019-06-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('0', 'Faculty'), ('1', 'Student'), ('2', 'Alumni'), ('3', 'Staff')], default='0', max_length=2),
        ),
    ]
