# Generated by Django 2.1.5 on 2019-01-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0004_auto_20190128_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometextpanel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
