# Generated by Django 2.2.1 on 2019-06-08 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('mechweb', '0004_eventhomepage_eventpage_eventpagegalleryimage_eventpagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FacultyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('office_contact_number', models.CharField(blank=True, max_length=20)),
                ('home_contact_number', models.CharField(blank=True, max_length=20)),
                ('office_address_line_1', models.CharField(blank=True, max_length=25)),
                ('home_address_line_1', models.CharField(blank=True, max_length=25)),
                ('email_id', models.EmailField(max_length=254)),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(choices=[('0', 'HAG'), ('1', 'Professor'), ('2', 'Assistant Professor'), ('3', 'Associate Professor'), ('4', 'Visiting Professor'), ('5', 'Professor On lien')], default='3', max_length=2)),
                ('website', models.URLField(max_length=250)),
                ('additional_roles', models.CharField(choices=[('2', 'Not Applicable'), ('1', 'HoD'), ('0', 'Director')], default='2', max_length=2)),
                ('disposal_committee', models.CharField(choices=[('4', 'Not Applicable'), ('0', 'Chairman'), ('1', 'Member'), ('2', 'External Member'), ('3', 'Non Member Secretary')], default='4', max_length=2)),
                ('laboratory_in_charge', models.CharField(choices=[('14', 'Not Applicable'), ('0', 'Advanced Manufacturing Laboratory'), ('1', 'CAD Laboratory'), ('2', 'Central Workshop'), ('3', 'Fluid Mechanics Laboratory'), ('4', 'IC Engines Laboratory'), ('5', 'Instrumentation and Control Laboratory'), ('6', 'Material Science Laboratory'), ('7', 'Tribology Laboratory'), ('8', 'Mechatronics and Robotics Laboratory'), ('9', 'Strength of Materials Laboratory'), ('10', 'Theory of Machines Laboratory'), ('11', 'Thermal Science Laboratory'), ('12', 'Turbo Machinary Laboratory'), ('13', 'Vibrations and Acoustics Laboratory')], default='14', max_length=2)),
                ('faculty_in_charge', models.CharField(choices=[('11', 'Not Applicable'), ('0', 'BTP Co ordinator'), ('1', 'MTP Co ordinator'), ('2', 'Central Workshop'), ('3', 'Library Committee'), ('4', 'Training and Placement'), ('5', 'Departmental Seminar Room'), ('6', 'Secretary Faculty Meeting'), ('7', 'PG Computational Lab'), ('8', 'Research Scholar Room'), ('9', 'Time Table Committee'), ('10', 'Departmental Website')], default='11', max_length=2)),
                ('disciplinary_committee', models.CharField(choices=[('4', 'Not Applicable'), ('0', 'Chairman'), ('1', 'Secretary'), ('2', 'Member Secretary'), ('3', 'Student Member')], default='4', max_length=2)),
                ('dupc', models.CharField(choices=[('6', 'Not Applicable'), ('0', 'Chairman'), ('1', 'Secretary'), ('2', 'Faculty Member'), ('3', 'External Member'), ('4', '3rd year BTech'), ('5', '2nd year BTech')], default='6', max_length=2)),
                ('dppc', models.CharField(choices=[('6', 'Not Applicable'), ('0', 'Chairman'), ('1', 'Secretary'), ('2', 'Faculty Member'), ('3', 'External Member'), ('4', 'PhD Student Member'), ('5', 'MTech Student Member')], default='6', max_length=2)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StaffHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Staff Home',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StaffPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('joining_year', models.DateField()),
                ('designation', models.CharField(choices=[('0', 'Administrative Staff'), ('1', 'Lab Staff'), ('2', 'Technicial staff'), ('3', 'Others')], default='1', max_length=2)),
                ('intro', models.CharField(max_length=250)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StudentHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Student Home',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StudentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('roll_no', models.IntegerField()),
                ('enrolment_year', models.DateField()),
                ('programme', models.CharField(choices=[('0', 'Bachelor'), ('1', 'Masters'), ('2', 'Research Scholar'), ('3', 'Other, e.g. PostDoc or N.A.')], max_length=2)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=25)),
                ('specialization', models.CharField(choices=[('0', 'Not Applicable'), ('1', 'Aerodynamics & Propulsion'), ('2', 'Computer Aided Manufacturing'), ('3', 'Computational Mechanics'), ('4', 'Fluids and Thermal'), ('5', 'Machine Design')], default='0', help_text='Not Applicable - for B.Tech, PhD and PostDocs', max_length=2)),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=250)),
                ('faculty_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_advisor', to='mechweb.FacultyPage')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StudentResearchInterestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='mechweb.StudentPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechweb_studentresearchinteresttag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('abstract', wagtail.core.fields.RichTextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=250)),
                ('co_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_guide', to='mechweb.FacultyPage')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide', to='mechweb.FacultyPage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='mechweb.StudentPage')),
                ('photo_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('photo_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('photo_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentPageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link', models.URLField(max_length=250)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mechweb.StudentPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='mechweb.StudentPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='studentpage',
            name='research_interests',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mechweb.StudentResearchInterestTag', to='taggit.Tag', verbose_name='Research Interests'),
        ),
        migrations.AddField(
            model_name='studentpage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StaffSkillag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='mechweb.StaffPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechweb_staffskillag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='staffpage',
            name='skills',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mechweb.StaffSkillag', to='taggit.Tag', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FacultyResearchInterestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='mechweb.FacultyPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechweb_facultyresearchinteresttag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='mechweb.FacultyPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='facultypage',
            name='research_interests',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mechweb.FacultyResearchInterestTag', to='taggit.Tag', verbose_name='Research Interests'),
        ),
        migrations.AddField(
            model_name='facultypage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FacultyAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link', models.URLField(max_length=250)),
                ('message', wagtail.core.fields.RichTextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_announcement', to='mechweb.FacultyPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
