# Generated by Django 2.2.1 on 2019-06-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0004_auto_20190608_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
