# Generated by Django 2.1.5 on 2019-01-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0005_auto_20190128_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometextpanel',
            name='content_type',
            field=models.CharField(choices=[('mini_article', 'mini_article')], default='mini_article', max_length=50),
        ),
    ]
