# Generated by Django 2.2.1 on 2019-06-10 06:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0008_auto_20190610_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcourse',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_courses', to='mechweb.CourseStructure'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='start_date',
            field=models.DateField(),
        ),
    ]
