# Generated by Django 2.1.5 on 2019-01-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0009_auto_20190129_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhomepage',
            name='featured_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_event', to='mechweb.EventPage'),
        ),
    ]
