# Generated by Django 2.2.1 on 2019-06-10 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0009_auto_20190610_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
