# Generated by Django 2.1.5 on 2019-01-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0010_eventhomepage_featured_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='sort_order',
        ),
    ]
