# Generated by Django 2.1.5 on 2019-01-30 08:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0011_auto_20190130_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhomepage',
            name='info',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
