# Generated by Django 2.1.5 on 2019-01-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0012_eventhomepage_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventhomepage',
            old_name='info',
            new_name='intro',
        ),
    ]
