# Generated by Django 2.2.1 on 2019-06-11 03:06

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0013_auto_20190610_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechhomepage',
            name='HOD_message',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
