# Generated by Django 2.2.1 on 2019-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0017_auto_20190611_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='labequipment',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='researchlabpage',
            name='lab_research_area',
            field=models.CharField(choices=[('0', 'Other'), ('1', 'Machine Design Engineering'), ('2', 'Manufacturing Engineering'), ('3', 'Thermal and Fluid Engineering')], default='a', max_length=2),
        ),
    ]
