# Generated by Django 2.1.5 on 2019-02-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0017_auto_20190204_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultypage',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='facultypage',
            name='office_address',
        ),
        migrations.AddField(
            model_name='facultypage',
            name='home_address_line_1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='facultypage',
            name='home_address_line_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facultypage',
            name='home_address_line_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facultypage',
            name='office_address_line_1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='facultypage',
            name='office_address_line_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facultypage',
            name='office_address_line_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='home_contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='office_contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
