# Generated by Django 2.2.1 on 2019-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0018_auto_20190611_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='course_page_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='course_type',
            field=models.CharField(choices=[('Departmental', (('0', 'Core course'), ('1', 'Department Elective'), ('2', 'Department Open Elective'))), ('Non-Departmental', (('3', 'Common course'), ('4', 'HSS Elective'), ('5', 'Open Elective')))], default='0', max_length=100),
        ),
    ]
