# Generated by Django 2.1.5 on 2019-02-04 10:06

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0018_auto_20190204_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultypage',
            name='research_interests',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mechweb.FacultyResearchInterestTag', to='taggit.Tag', verbose_name='research_interests'),
        ),
    ]
