# Generated by Django 2.2.1 on 2019-06-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0021_auto_20190612_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnuspage',
            name='is_exchange',
            field=models.BooleanField(default=False, verbose_name='International Student'),
        ),
        migrations.AddField(
            model_name='studentpage',
            name='is_exchange',
            field=models.BooleanField(default=False, verbose_name='International Student'),
        ),
    ]
