# Generated by Django 2.1.5 on 2019-02-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0021_auto_20190210_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultypage',
            old_name='faculty_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='facultypage',
            name='website',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
