# Generated by Django 2.2.1 on 2019-06-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0022_auto_20190612_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationpage',
            old_name='vol_issue',
            new_name='pub_issue',
        ),
        migrations.RemoveField(
            model_name='publicationpage',
            name='pages',
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='citations',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='page_end',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='page_start',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='pub_vol',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
