# Generated by Django 2.2.1 on 2019-06-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0023_auto_20190612_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyAward',
        ),
    ]
