# Generated by Django 2.2.1 on 2019-06-13 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('mechweb', '0024_delete_facultyaward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('other_recipients', models.CharField(max_length=100)),
                ('award_title', models.CharField(max_length=100)),
                ('award_description', wagtail.core.fields.RichTextField(blank=True)),
                ('award_type', models.CharField(choices=[('0', 'Faculty Awarded'), ('1', 'Best Paper'), ('2', 'Other')], default='0', max_length=2)),
                ('award_time', models.DateField(default=django.utils.timezone.now)),
                ('conferrer', models.CharField(max_length=100)),
                ('conferrer_description', wagtail.core.fields.RichTextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=250)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_fac', to='mechweb.FacultyPage')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='mechweb.AwardHomePage')),
            ],
            options={
                'ordering': ['-award_time'],
            },
        ),
    ]
