# Generated by Django 2.2.1 on 2019-06-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0025_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='other_recipients',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
