# Generated by Django 2.2.1 on 2019-06-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0026_auto_20190613_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpage',
            name='designation',
            field=models.CharField(choices=[('0', 'Jr. Assistant'), ('1', 'Jr. Superintendent'), ('2', 'Jr. Technical Superintendent'), ('3', 'Jr. Technician'), ('4', 'Technical Officer Gr I'), ('5', 'Technical Officer Gr II'), ('6', 'Technical Superintendent'), ('7', 'Junior Technical Officer'), ('8', 'Asst. Workshop Superintendent'), ('9', 'PostDoc'), ('10', 'Others')], default='10', max_length=2),
        ),
    ]
