# Generated by Django 2.1.5 on 2019-02-10 09:25

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0027_publicationhomepage_publicationpage_publicationpagefaculty_publicationpagelink_publicationpagestuden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='mechweb.PublicationHomePage'),
        ),
    ]
