# Generated by Django 2.2.1 on 2019-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0027_auto_20190614_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('0', 'Faculty'), ('1', 'Student'), ('2', 'Alumni'), ('3', 'Staff')], default='0', max_length=2),
        ),
    ]
