# Generated by Django 2.2.1 on 2019-06-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0030_auto_20190614_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='labequipment',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
