# Generated by Django 2.2.1 on 2019-06-15 11:41

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0031_labequipment_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultypage',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='mechhomepage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mechhomepage',
            name='intro',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
