# Generated by Django 2.1.5 on 2019-02-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0031_projectpagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Consultancy', 'Consultancy')], default='Academic', max_length=20),
        ),
    ]
