# Generated by Django 2.2.1 on 2019-06-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0032_auto_20190615_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnuspage',
            name='roll_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('0', 'Faculty'), ('1', 'Student'), ('2', 'Alumni'), ('3', 'Staff'), ('4', 'Others')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='roll_no',
            field=models.IntegerField(blank=True),
        ),
    ]
