# Generated by Django 2.1.5 on 2019-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0032_projectpage_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpage',
            name='roll_no',
            field=models.IntegerField(default=160103001),
        ),
    ]
