# Generated by Django 2.2.1 on 2019-06-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0033_auto_20190615_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.CharField(default='000000000', help_text='Only students required to provide their roll no. Others may leave "000000000" but not blank', max_length=10, verbose_name='Roll Number/Employee Number'),
        ),
    ]
