# Generated by Django 2.1.5 on 2019-02-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0034_auto_20190213_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='eligible_programmes',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Masters', 'Masters'), ('Research_Scholar', 'Research_Scholar'), ('PostDoc', 'PostDoc')], max_length=100, verbose_name='Minimum qualification'),
        ),
    ]
