# Generated by Django 2.1.5 on 2019-02-17 09:12

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('taggit', '0002_auto_20150616_2121'),
        ('mechweb', '0035_auto_20190213_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniHomePage',
            fields=[
                ('studenthomepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mechweb.StudentHomePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('mechweb.studenthomepage',),
        ),
        migrations.CreateModel(
            name='AlumniInterestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnusPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('contact_number_2', models.CharField(blank=True, max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('email_id_2', models.EmailField(max_length=254)),
                ('address_line_1', models.CharField(blank=True, max_length=25)),
                ('address_line_2', models.CharField(blank=True, max_length=50)),
                ('address_line_3', models.CharField(blank=True, max_length=100)),
                ('enrolment_year', models.DateField()),
                ('programme', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Masters', 'Masters'), ('Research_Scholar', 'Research_Scholar'), ('PostDoc', 'PostDoc')], default='Bachelor', max_length=25)),
                ('roll_no', models.IntegerField(default=160103001)),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('website', models.URLField(max_length=250, null=True)),
                ('interests', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mechweb.AlumniInterestTag', to='taggit.Tag', verbose_name='Interests')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AlumnusPageJobDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=20)),
                ('work_details', models.CharField(blank=True, max_length=500)),
                ('link', models.URLField(max_length=250)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_details', to='mechweb.AlumnusPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistinguishedAlumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('about', wagtail.core.fields.RichTextField()),
                ('distinguished_alumnus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distinguished_alumnus', to='mechweb.AlumnusPage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='distinguished_alumni', to='mechweb.AlumniHomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alumniinteresttag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_tagged_items', to='mechweb.AlumnusPage'),
        ),
        migrations.AddField(
            model_name='alumniinteresttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechweb_alumniinteresttag_items', to='taggit.Tag'),
        ),
    ]
