# Generated by Django 2.2.1 on 2019-05-31 03:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0036_auto_20190217_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseannouncementpage',
            name='announcement',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='distinguishedalumni',
            name='about',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpagefaculty',
            name='project_statement',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpagestudent',
            name='project_statement',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publicationpagefaculty',
            name='research_statement',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publicationpagestudent',
            name='research_statement',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='researchlabstudents',
            name='research_statement',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
