# Generated by Django 2.2.1 on 2019-06-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0037_auto_20190531_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultypage',
            name='additional_roles',
            field=models.CharField(choices=[('HoD', 'HoD'), ('Director', 'Director'), ('HAG', 'HAG')], default='Assistant_Professor', max_length=25),
        ),
    ]
