# Generated by Django 2.2.1 on 2019-06-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0039_auto_20190601_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultypage',
            name='office_address_line_2',
        ),
        migrations.RemoveField(
            model_name='facultypage',
            name='office_address_line_3',
        ),
    ]
