# Generated by Django 2.2.1 on 2019-06-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('mechweb', '0040_auto_20190617_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestCategories',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('category', models.CharField(choices=[('0', 'Other'), ('1', 'Machine Design Engineering'), ('2', 'Manufacturing Engineering'), ('3', 'Thermal and Fluid Engineering')], default='0', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='researchlabpage',
            name='lab_research_area',
        ),
        migrations.AddField(
            model_name='facultypage',
            name='fac_research_categories',
            field=models.ManyToManyField(blank=True, to='mechweb.InterestCategories'),
        ),
    ]
