# Generated by Django 2.2.1 on 2019-06-01 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0041_auto_20190601_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyhomepage',
            name='head_of_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_hept', to='mechweb.FacultyPage'),
        ),
    ]
