# Generated by Django 2.2.1 on 2019-06-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0041_auto_20190617_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutiitgmech',
            old_name='About',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='aboutiitgmech',
            old_name='History',
            new_name='history',
        ),
    ]
