# Generated by Django 2.2.1 on 2019-06-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0042_facultyhomepage_head_of_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyhomepage',
            name='head_of_dept',
        ),
    ]
