# Generated by Django 2.2.1 on 2019-06-01 06:59

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0043_remove_facultyhomepage_head_of_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultypagelink',
            name='message',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='FacultyPublicationDocument',
        ),
    ]
