# Generated by Django 2.2.1 on 2019-06-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('mechweb', '0045_auto_20190618_0459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestCategories',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='InterestCategoriesHomePage',
            new_name='CategoriesHome',
        ),
    ]
