# Generated by Django 2.2.1 on 2019-06-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0046_auto_20190618_0523'),
        ('mechweb', '0042_auto_20190617_1518'),
    ]

    operations = [
    ]
