# Generated by Django 2.2.1 on 2019-07-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0046_auto_20190618_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='pub_type',
            field=models.CharField(choices=[('0', 'Patent'), ('1', 'Conference Publication'), ('2', 'Journal Publication'), ('3', 'Books'), ('4', 'Book Chapters'), ('5', 'Poster')], default='0', max_length=2),
        ),
    ]
