# Generated by Django 2.2.1 on 2019-06-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0047_auto_20190601_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyannouncement',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
