# Generated by Django 2.2.1 on 2019-06-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0047_auto_20190601_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffhomepage',
            name='use_other_template',
            field=models.IntegerField(default=3),
        ),
    ]
