# Generated by Django 2.2.1 on 2019-06-01 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0048_facultyannouncement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyannouncement',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
