# Generated by Django 2.2.1 on 2019-06-01 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0049_facultyannouncement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyannouncement',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
