# Generated by Django 2.2.1 on 2019-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0049_projectpage_alt_pi_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='budget',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
