# Generated by Django 2.2.1 on 2019-06-01 11:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0050_auto_20190601_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhomepage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
