# Generated by Django 2.2.1 on 2019-07-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0051_auto_20190718_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchlabpage',
            name='intro',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
