# Generated by Django 2.2.1 on 2019-06-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0051_researchhomepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='labequipment',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
