# Generated by Django 2.2.1 on 2019-06-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0052_labequipment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labequipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='labequipment',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='labequipment',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='labequipment',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='labequipment',
            name='photo_5',
        ),
    ]
