# Generated by Django 2.2.1 on 2019-07-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0052_auto_20190718_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='award',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_fac', to='mechweb.FacultyPage'),
        ),
    ]
