# Generated by Django 2.2.1 on 2019-06-02 01:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0053_auto_20190601_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
