# Generated by Django 2.2.1 on 2019-07-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0053_auto_20190718_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='alt_recipient_text',
            field=models.CharField(blank=True, help_text="Use this only if you can't add faculty", max_length=1000),
        ),
    ]
