# Generated by Django 2.2.1 on 2019-07-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0054_award_alt_recipient_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
