# Generated by Django 2.2.1 on 2019-06-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0054_projectpage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpage',
            name='hostel_address_line_2',
        ),
        migrations.RemoveField(
            model_name='studentpage',
            name='hostel_address_line_3',
        ),
        migrations.RemoveField(
            model_name='studentpage',
            name='website',
        ),
    ]
