# Generated by Django 2.2.1 on 2019-07-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0055_auto_20190718_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='page_end',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='page_start',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
