# Generated by Django 2.2.1 on 2019-06-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0055_auto_20190602_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpage',
            name='website',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
