# Generated by Django 2.2.1 on 2019-06-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0057_studentproject_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnuspage',
            old_name='body',
            new_name='description',
        ),
    ]
