# Generated by Django 2.2.1 on 2019-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0057_auto_20190719_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgrammes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('0', 'Bachelor'), ('1', 'Masters'), ('2', 'Research Scholar'), ('3', 'Other')], default='0', max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSpecializations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('0', 'Not Applicable'), ('1', 'Aerodynamics & Propulsion'), ('2', 'Manufacturing Science and Engineering'), ('3', 'Computational Mechanics'), ('4', 'Fluids and Thermal'), ('5', 'Machine Design')], default='0', max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Departmental', (('0', 'Core course'), ('1', 'Department Elective'), ('2', 'Department Open Elective'))), ('Non-Departmental', (('3', 'Common course'), ('4', 'HSS Elective'), ('5', 'Open Elective')))], default='0', max_length=2, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='eligible_programmes',
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='eligible_specializations',
        ),
        migrations.AddField(
            model_name='coursepage',
            name='course_type',
            field=models.ManyToManyField(blank=True, related_name='course', to='mechweb.CourseTypes'),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='eligible_programmes',
            field=models.ManyToManyField(blank=True, related_name='course', to='mechweb.CourseProgrammes'),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='eligible_specializations',
            field=models.ManyToManyField(blank=True, related_name='course', to='mechweb.CourseSpecializations'),
        ),
    ]
