# Generated by Django 2.2.1 on 2019-06-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0058_auto_20190602_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultypage',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
