# Generated by Django 2.2.1 on 2019-06-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0059_facultypage_leaving_date'),
        ('mechweb', '0048_staffhomepage_use_other_template'),
    ]

    operations = [
    ]
