# Generated by Django 2.2.1 on 2019-07-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('mechweb', '0061_auto_20190719_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='course_type',
        ),
        migrations.AddField(
            model_name='coursepage',
            name='course_type',
            field=models.CharField(choices=[('Departmental', (('0', 'Core course'), ('1', 'Department Elective'), ('2', 'Department Open Elective'))), ('Non-Departmental', (('3', 'Common course'), ('4', 'HSS Elective'), ('5', 'Open Elective')))], default='0', max_length=2),
        ),
        migrations.DeleteModel(
            name='CourseTypes',
        ),
    ]
