# Generated by Django 2.2.1 on 2019-06-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0062_auto_20190605_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechhomepagegalleryimage',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='hometextpanel',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='designation',
            field=models.CharField(choices=[('0', 'Administrative Staff'), ('1', 'Lab Staff'), ('2', 'Technicial staff'), ('3', 'Others')], default='1', max_length=2),
        ),
    ]
