# Generated by Django 2.2.1 on 2019-06-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0065_auto_20190605_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometextpanel',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
