# Generated by Django 2.2.1 on 2019-06-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0066_auto_20190605_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometextpanel',
            name='content_type',
            field=models.CharField(choices=[('0', 'News'), ('1', 'Notifications'), ('2', 'Others')], default='0', max_length=50),
        ),
    ]
