# Generated by Django 2.2.1 on 2019-07-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('mechweb', '0067_auto_20190719_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursespecializations',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='CourseProgrammes',
        ),
        migrations.DeleteModel(
            name='CourseSpecializations',
        ),
    ]
