# Generated by Django 2.2.1 on 2019-06-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0067_auto_20190605_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='download_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='pub_type',
            field=models.CharField(choices=[('0', 'Poster'), ('1', 'Conference Publication'), ('2', 'Journal Publication'), ('3', 'Patent'), ('4', 'Books'), ('5', 'Book Chapters')], default='0', max_length=2),
        ),
    ]
