# Generated by Django 2.2.1 on 2019-07-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0068_auto_20190719_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
