# Generated by Django 2.2.1 on 2019-07-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0068_auto_20190719_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('0', 'other'), ('1', 'Machine Design Engineering'), ('2', 'Manufacturing Engineering'), ('3', 'Thermal and Fluid Engineering')], default='0', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
