# Generated by Django 2.2.1 on 2019-06-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0069_auto_20190605_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpagegalleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
