# Generated by Django 2.2.1 on 2019-07-20 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0070_staffpage_responsibilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyPreviousWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('about', wagtail.core.fields.RichTextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('work_type', models.CharField(choices=[('0', 'Undergrad'), ('1', 'Masters'), ('2', 'PhD'), ('3', 'PostDoc'), ('4', 'Work')], default='0', max_length=2)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_prev_work', to='mechweb.FacultyPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
