# Generated by Django 2.2.1 on 2019-07-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0071_facultypreviouswork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
