# Generated by Django 2.2.1 on 2019-06-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0073_auto_20190606_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestructure',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='eventhomepage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='facultyhomepage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='researchhomepage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='staffhomepage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='studenthomepage',
            name='nav_order',
        ),
    ]
