# Generated by Django 2.2.1 on 2019-12-08 07:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0073_auto_20190803_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultypage',
            name='on_lien',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='designation',
            field=models.CharField(choices=[('0', 'HAG'), ('1', 'Professor'), ('2', 'Assistant Professor'), ('3', 'Associate Professor'), ('4', 'Visiting Professor')], default='3', max_length=2),
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='leaving_date',
            field=models.DateField(blank=True, default=datetime.date(2119, 11, 14)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to=settings.AUTH_USER_MODEL),
        ),
    ]
