# Generated by Django 2.2.1 on 2019-12-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0074_auto_20191208_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultypage',
            name='on_insti',
            field=models.CharField(blank=True, help_text='Institute name', max_length=500, verbose_name='Visiting from/On lien to'),
        ),
        migrations.AddField(
            model_name='facultypage',
            name='on_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project_type',
            field=models.CharField(choices=[('1', 'Sponsored'), ('0', 'Consultancy')], default='1', max_length=20),
        ),
    ]
