# Generated by Django 2.2.1 on 2019-06-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0075_auto_20190606_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpage',
            name='specialization',
            field=models.CharField(choices=[('0', 'Not Applicable'), ('1', 'Masters'), ('2', 'Research Scholar'), ('3', 'PostDoc')], default='0', help_text='Not Applicable - for B.Tech, PhD and PostDocs', max_length=2),
        ),
    ]
