# Generated by Django 2.2.1 on 2019-06-06 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0076_studentpage_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepagefaculty',
            name='session',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='specialization',
            field=models.CharField(choices=[('0', 'Not Applicable'), ('1', 'Aerodynamics & Propulsion'), ('2', 'Computer Aided Manufacturing'), ('3', 'Computational Mechanics'), ('4', 'Fluids and Thermal'), ('5', 'Machine Design')], default='0', help_text='Not Applicable - for B.Tech, PhD and PostDocs', max_length=2),
        ),
    ]
