# Generated by Django 2.2.1 on 2019-06-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0077_auto_20190606_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='course_type',
            field=models.CharField(choices=[('Departmental', (('0', 'Core course'), ('1', 'Department Elective'), ('2', 'Department Open Elective'))), ('Non-Departmental', (('3', 'Common course'), ('4', 'HSS Elective'), ('4', 'Open Elective')))], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='eligible_programmes',
            field=models.CharField(choices=[('0', 'Bachelor'), ('1', 'Masters'), ('2', 'Research Scholar'), ('3', 'PostDoc')], default='0', help_text='Minimum qualification needed to take course', max_length=100),
        ),
    ]
