# Generated by Django 2.2.1 on 2019-06-09 08:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('mechweb', '0078_auto_20190606_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechhomepage',
            name='HOD_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='mechhomepage',
            name='HOD_message',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
