# Generated by Django 2.2.1 on 2020-02-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0078_auto_20200209_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechhomepage',
            name='donation_link',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
