# Generated by Django 2.2.1 on 2019-06-07 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mechweb', '0078_auto_20190606_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultypage',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='facultypage',
            name='last_name',
            field=models.CharField(default='Last_NAME', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultypage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
