# Generated by Django 2.2.1 on 2019-06-07 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0079_auto_20190607_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultypage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='website',
            field=models.URLField(default='www.iitg.ac.in', max_length=250, null=True),
        ),
    ]
