# Generated by Django 2.2.1 on 2019-06-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0080_researchlabpage_research_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchlabpage',
            name='research_area',
            field=models.CharField(choices=[('a', 'Thermal and Fluid Engineering'), ('b', 'Machine Design Engineering'), ('c', 'Manufacturing Engineering')], default='a', max_length=2),
        ),
    ]
