# Generated by Django 2.2.1 on 2019-06-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0080_auto_20190607_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultypage',
            name='website',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
