# Generated by Django 2.2.1 on 2019-06-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0081_auto_20190607_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultypage',
            name='website',
            field=models.URLField(default='www.iitg.ac.in', max_length=250),
            preserve_default=False,
        ),
    ]
