# Generated by Django 2.2.1 on 2020-02-09 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0081_committeehomepage_committeepage_committeepagefaculty_committeepagelink_committeepageothermmeber_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeepage',
            name='tenure_end',
            field=models.DateField(default=datetime.datetime(2021, 2, 8, 12, 30, 45, 874625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='designation',
            field=models.CharField(choices=[('0', 'Jr. Assistant'), ('1', 'Jr. Superintendent'), ('2', 'Jr. Technical Superintendent'), ('3', 'Jr. Technician'), ('6', 'Technical Officer Gr I'), ('5', 'Technical Officer Gr II'), ('4', 'Technical Superintendent'), ('7', 'Junior Technical Officer'), ('8', 'Asst. Workshop Superintendent'), ('9', 'PostDoc'), ('10', 'Others')], default='10', max_length=2),
        ),
    ]
