# Generated by Django 2.2.1 on 2019-06-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0082_labhomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='Authors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='pages',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='pub_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='vol_issue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
