# Generated by Django 2.2.1 on 2019-06-07 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mechweb', '0082_auto_20190607_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpage',
            old_name='hostel_address_line_1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='studentpage',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='studentpage',
            name='last_name',
            field=models.CharField(default='Last name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='programme',
            field=models.CharField(choices=[('0', 'Bachelor'), ('1', 'Masters'), ('2', 'Research Scholar'), ('3', 'PostDoc')], max_length=2),
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
