# Generated by Django 2.2.1 on 2020-02-09 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0082_auto_20200209_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnuspage',
            name='dppc',
        ),
        migrations.RemoveField(
            model_name='alumnuspage',
            name='dupc',
        ),
        migrations.RemoveField(
            model_name='alumnuspage',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='alumnuspage',
            name='sae',
        ),
        migrations.RemoveField(
            model_name='facultypage',
            name='disciplinary_committee',
        ),
        migrations.RemoveField(
            model_name='facultypage',
            name='disposal_committee',
        ),
        migrations.RemoveField(
            model_name='facultypage',
            name='dppc',
        ),
        migrations.RemoveField(
            model_name='facultypage',
            name='dupc',
        ),
        migrations.RemoveField(
            model_name='facultypage',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='facultypage',
            name='sae',
        ),
        migrations.RemoveField(
            model_name='studentpage',
            name='dppc',
        ),
        migrations.RemoveField(
            model_name='studentpage',
            name='dupc',
        ),
        migrations.RemoveField(
            model_name='studentpage',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='studentpage',
            name='sae',
        ),
        migrations.AddField(
            model_name='alumnuspage',
            name='leaving_year',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 13, 25, 9, 633454, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='studentpage',
            name='leaving_year',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 13, 25, 9, 633454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='committeepage',
            name='tenure_end',
            field=models.DateField(default=datetime.datetime(2021, 2, 8, 13, 25, 9, 654793, tzinfo=utc)),
        ),
    ]
