# Generated by Django 2.2.1 on 2019-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0083_auto_20190611_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='pub_journal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='vol_issue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
