# Generated by Django 2.2.1 on 2019-06-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0083_auto_20190607_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpage',
            name='user',
        ),
        migrations.AlterField(
            model_name='alumnuspage',
            name='programme',
            field=models.CharField(choices=[('0', 'Bachelor'), ('1', 'Masters'), ('2', 'Research Scholar'), ('3', 'Other, e.g. PostDoc or N.A.')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='eligible_programmes',
            field=models.CharField(choices=[('0', 'Bachelor'), ('1', 'Masters'), ('2', 'Research Scholar'), ('3', 'Other, e.g. PostDoc or N.A.')], default='0', help_text='Minimum qualification needed to take course', max_length=100),
        ),
        migrations.AlterField(
            model_name='hometextpanel',
            name='content_type',
            field=models.CharField(choices=[('0', 'News'), ('1', 'Announcements'), ('2', 'Others')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='programme',
            field=models.CharField(choices=[('0', 'Bachelor'), ('1', 'Masters'), ('2', 'Research Scholar'), ('3', 'Other, e.g. PostDoc or N.A.')], max_length=2),
        ),
    ]
