# Generated by Django 2.2.1 on 2020-02-10 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0092_auto_20200210_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutiitgmech',
            name='about',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='aboutiitgmech',
            name='history',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='aboutiitgmech',
            name='vision',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='alumnuspage',
            name='leaving_year',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 15, 34, 14, 927906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='committeepage',
            name='tenure_end',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 15, 34, 14, 949781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='leaving_year',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 15, 34, 14, 927906, tzinfo=utc)),
        ),
    ]
