# Generated by Django 2.2.1 on 2020-02-10 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0096_auto_20200210_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnuspage',
            name='leaving_year',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 17, 3, 30, 850544, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='committeepage',
            name='tenure_end',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 17, 3, 30, 872326, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='five_sem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='four_sem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='one_sem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='seven_sem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='six_sem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='three_sem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='two_sem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='zero_sem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='leaving_year',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 17, 3, 30, 850544, tzinfo=utc)),
        ),
    ]
