# Generated by Django 2.2.9 on 2020-02-12 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0101_auto_20200211_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultypage',
            name='on_depute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumnuspage',
            name='leaving_year',
            field=models.DateField(default=datetime.datetime(2024, 2, 11, 8, 43, 29, 289109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='committeepage',
            name='tenure_end',
            field=models.DateField(default=datetime.datetime(2021, 2, 11, 8, 43, 29, 310639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='designation',
            field=models.CharField(choices=[('0', 'HAG'), ('1', 'Professor'), ('3', 'Associate Professor'), ('2', 'Assistant Professor'), ('4', 'Visiting Professor')], default='3', max_length=2),
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='on_insti',
            field=models.CharField(blank=True, help_text='Institute name', max_length=500, verbose_name='Visiting from/On lien to/On deputation to'),
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='leaving_year',
            field=models.DateField(default=datetime.datetime(2024, 2, 11, 8, 43, 29, 289109, tzinfo=utc)),
        ),
    ]
