# Generated by Django 3.1.1 on 2020-09-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('mechweb', '0107_auto_20200919_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeepage',
            name='minutes_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='committeepagelink',
            name='link_text',
            field=models.CharField(default='example', max_length=250),
            preserve_default=False,
        ),
    ]
