# Generated by Django 3.1.2 on 2020-10-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0110_auto_20201012_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labequipment',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labequipment',
            name='date_of_procurement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
