# Generated by Django 3.1.2 on 2020-10-20 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0112_auto_20201018_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchLabIntern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=250)),
                ('institute', models.CharField(max_length=250)),
                ('start', models.DateField(default=django.utils.timezone.now)),
                ('end', models.DateField(default=django.utils.timezone.now)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='interns', to='mechweb.researchlabpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='studentpage',
            name='research_interests',
        ),
        migrations.AlterField(
            model_name='alumnuspage',
            name='leaving_year',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='venue',
            field=models.CharField(blank=True, choices=[('0', 'Seminar hall'), ('1', 'ME new meeting room'), ('2', 'Other'), ('3', 'Online')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='faculty_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_advisor', to='mechweb.facultypage', verbose_name='Main supervisor/Faculty Advisor'),
        ),
        migrations.AlterField(
            model_name='studentpage',
            name='leaving_year',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='StudentResearchInterestTag',
        ),
    ]
