# Generated by Django 3.1.2 on 2020-11-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0113_auto_20201020_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpage',
            name='designation',
            field=models.CharField(choices=[('0', 'Jr. Assistant'), ('1', 'Jr. Superintendent'), ('2', 'Jr. Technical Superintendent'), ('3', 'Jr. Technician'), ('4', 'Technical Superintendent'), ('5', 'Sr. Assistant'), ('6', 'Sr. Superintendent'), ('7', 'Sr. Technical Superintendent'), ('8', 'Sr. Technician'), ('9', 'Technical Officer Gr I'), ('10', 'Technical Officer Gr II'), ('11', 'Junior Technical Officer'), ('12', 'Asst. Workshop Superintendent'), ('13', 'Senior Technical Officer'), ('14', 'PostDoc'), ('15', 'Others')], default='15', max_length=2),
        ),
    ]
