# Generated by Django 3.1.2 on 2020-11-12 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0114_auto_20201108_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpage',
            name='joining_year',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
