# Generated by Django 3.1.2 on 2020-11-17 11:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0115_auto_20201112_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomepage',
            name='btech_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='studenthomepage',
            name='mtech_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='studenthomepage',
            name='phd_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
