# Generated by Django 3.1.1 on 2020-12-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0115_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
    ]
