# Generated by Django 3.1.2 on 2020-12-19 08:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('mechweb', '0116_auto_20201117_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_faculty', to='mechweb.facultypage'),
        ),
        migrations.CreateModel(
            name='AwardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('other_recipients', models.CharField(blank=True, max_length=100)),
                ('award_title', models.CharField(max_length=500)),
                ('award_description', wagtail.core.fields.RichTextField(blank=True)),
                ('award_type', models.CharField(choices=[('0', 'Faculty Awarded'), ('1', 'Best Paper'), ('2', 'Other')], default='0', max_length=2)),
                ('award_time', models.CharField(blank=True, max_length=100)),
                ('conferrer', models.CharField(max_length=200)),
                ('conferrer_description', wagtail.core.fields.RichTextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=250)),
                ('alt_recipient_text', models.CharField(blank=True, help_text="Use this only if you can't add faculty", max_length=1000)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_fac', to='mechweb.facultypage')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
