# Generated by Django 3.1.1 on 2020-12-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('mechweb', '0116_auto_20201215_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectiveTimePeriod',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True)),
            ],
            options={
                'verbose_name': 'Effective Time Period',
                'verbose_name_plural': 'Effective Time Periods',
            },
            bases=('wagtailcore.page',),
        ),
    ]
