# Generated by Django 3.1.2 on 2020-12-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0117_auto_20201219_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Award',
        ),
    ]
