# Generated by Django 3.1.1 on 2020-12-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0117_effectivetimeperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectivetimeperiod',
            name='start_time',
            field=models.DateField(),
        ),
    ]
