# Generated by Django 3.1.2 on 2021-01-16 17:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('mechweb', '0118_delete_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAnnouncementHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'News and Announcements Home',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsAnnouncementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, max_length=50)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('date', models.DateTimeField()),
                ('info_type', models.CharField(choices=[('0', 'News'), ('1', 'Announcements'), ('2', 'Others')], default='0', max_length=50)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News or Announcement',
            },
            bases=('wagtailcore.page',),
        ),
    ]
