# Generated by Django 3.1.1 on 2020-12-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0120_auto_20201216_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectivetimeperiod',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
