# Generated by Django 3.1.2 on 2021-02-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0120_auto_20210116_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultypage',
            name='google_scholar_profile_link',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='facultypage',
            name='researchgate_profile_link',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='facultypage',
            name='scopus_profile_link',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
