# Generated by Django 3.1.1 on 2020-12-22 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('mechweb', '0122_programspecialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('lectures', models.IntegerField(verbose_name='L')),
                ('tutorials', models.IntegerField(verbose_name='T')),
                ('practicals', models.IntegerField(verbose_name='P')),
                ('credits', models.IntegerField(verbose_name='C')),
                ('course_type', models.CharField(choices=[('Departmental', (('0', 'Core course'), ('1', 'Department Elective'), ('2', 'Department Open Elective'))), ('Non-Departmental', (('3', 'Common course'), ('4', 'HSS Elective'), ('5', 'Open Elective')))], default='0', max_length=2)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('course_page_link', models.URLField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Syllabus')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CourseFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('session', models.DateField(default=django.utils.timezone.now, verbose_name='Instruction start date')),
                ('introduction', wagtail.core.fields.RichTextField(blank=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_instructors', to='mechweb.facultypage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructors', to='mechweb.course')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('announcement', wagtail.core.fields.RichTextField(blank=True, max_length=250)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_announcements', to='mechweb.course')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
