# Generated by Django 3.1.2 on 2021-02-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0123_auto_20210223_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='faculty_incharge',
        ),
    ]
