# Generated by Django 3.1.1 on 2020-12-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('mechweb', '0123_course_courseannouncement_coursefaculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sem', models.CharField(max_length=50, verbose_name='Semester Number')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
            bases=('wagtailcore.page',),
        ),
    ]
