# Generated by Django 3.1.1 on 2020-12-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0124_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='sem',
            new_name='semester_number',
        ),
    ]
