# Generated by Django 3.1.1 on 2020-12-30 12:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0125_auto_20201222_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
