# Generated by Django 3.1.2 on 2021-03-18 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mechweb.models
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('wagtailimages', '0022_uploadedimage'),
        ('mechweb', '0126_outreach_outreachcustomfaculty_outreachfaculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Academics',
                'verbose_name_plural': 'Academics',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('lectures', models.IntegerField(verbose_name='L')),
                ('tutorials', models.IntegerField(verbose_name='T')),
                ('practicals', models.IntegerField(verbose_name='P')),
                ('credits', models.IntegerField(verbose_name='C')),
                ('course_type', models.CharField(choices=[('Departmental', (('0', 'Core course'), ('1', 'Department Elective'), ('2', 'Department Open Elective'))), ('Non-Departmental', (('3', 'Common course'), ('4', 'HSS Elective'), ('5', 'Open Elective')))], default='0', max_length=2)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('course_page_link', models.URLField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Syllabus')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EffectiveTimePeriod',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('is_latest', models.BooleanField(default=False, verbose_name='Is this latest course structure?')),
            ],
            options={
                'verbose_name': 'Effective Time Period',
                'verbose_name_plural': 'Effective Time Periods',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('intro', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('body', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramSpecialization',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('intro', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('body', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Program Specialization',
                'verbose_name_plural': 'Program Specializations',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('semester_number', models.CharField(max_length=50, verbose_name='Semester Number')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StudentBatch',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('enrollment_year', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1994), mechweb.models.max_value_current_year], verbose_name='year')),
                ('table_view', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Student Batch',
                'verbose_name_plural': 'Student Batches',
                'ordering': ['-title'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Students',
                'verbose_name_plural': 'Students',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('webmail', models.EmailField(max_length=254, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=254, verbose_name='Personal Email ID')),
                ('roll_no', models.IntegerField(blank=True)),
                ('enrollment_year', models.DateField(default=django.utils.timezone.now)),
                ('leaving_year', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_exchange', models.BooleanField(default=False, verbose_name='International Student')),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('hostel_address', models.CharField(blank=True, max_length=264)),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('co_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_supervisor', to='mechweb.facultypage', verbose_name='Co-supervisor')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='mechweb.facultypage', verbose_name='Main supervisor/Faculty Advisor')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramTestimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('testimonial', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='mechweb.program')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramSpecializationTestimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('testimonial', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='mechweb.programspecialization')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('full_name', models.CharField(max_length=264)),
                ('website', models.URLField(blank=True)),
                ('supervisor_type', models.CharField(choices=[('supervisor', 'Supervisor/Faculty Advisor'), ('co_supervisor', 'Co-supervisor')], default='co_supervisor', max_length=264)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_supervisor', to='mechweb.student')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('current', models.BooleanField(default=True, verbose_name='Current Instructor?')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_instructors', to='mechweb.facultypage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructors', to='mechweb.course')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('announcement', wagtail.core.fields.RichTextField(blank=True, max_length=250)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_announcements', to='mechweb.course')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
