# Generated by Django 3.1.1 on 2020-12-30 12:37

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0126_program_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
