# Generated by Django 3.1.1 on 2020-12-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0128_programspecialization_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effectivetimeperiod',
            name='end',
        ),
        migrations.RemoveField(
            model_name='effectivetimeperiod',
            name='start',
        ),
    ]
