# Generated by Django 3.1.2 on 2021-05-20 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0130_projectstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsannouncementpage',
            name='badge',
            field=models.CharField(blank=True, choices=[('0', 'NEW'), ('1', 'IMPORTANT'), ('2', 'CLOSING SOON')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newsannouncementpage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
