# Generated by Django 3.1.1 on 2021-01-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('mechweb', '0132_auto_20210118_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Acadmic Course Structure',
                'verbose_name_plural': 'Acadmic Course Structures',
            },
            bases=('wagtailcore.page',),
        ),
    ]
