# Generated by Django 3.1.2 on 2021-07-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0133_facultypage_irins_profile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.IntegerField(default=2, help_text='Program duration in years'),
        ),
        migrations.AddField(
            model_name='program',
            name='has_alumni_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programspecialization',
            name='duration',
            field=models.IntegerField(default=2, help_text='Program duration in years'),
        ),
        migrations.AddField(
            model_name='programspecialization',
            name='has_alumni_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentbatch',
            name='alumni_batch',
            field=models.BooleanField(default=False, verbose_name='Move to Alumni Corner'),
        ),
    ]
