# Generated by Django 3.1.2 on 2021-02-28 19:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mechweb.models
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('mechweb', '0133_academics'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBatch',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('enrollment_year', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1994), mechweb.models.max_value_current_year], verbose_name='year')),
                ('table_view', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Student Batch',
                'verbose_name_plural': 'Student Batches',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Students',
                'verbose_name_plural': 'Students',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Personal Email ID')),
                ('roll_no', models.IntegerField(blank=True)),
                ('enrollment_year', models.DateField(default=django.utils.timezone.now)),
                ('leaving_year', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_exchange', models.BooleanField(default=False, verbose_name='International Student')),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('hostel_address', models.CharField(blank=True, max_length=25)),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=250)),
                ('co_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_supervisor', to='mechweb.facultypage', verbose_name='Co-supervisor')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='mechweb.facultypage', verbose_name='Main supervisor/Faculty Advisor')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CustomSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('full_name', models.CharField(max_length=264)),
                ('website', models.URLField(blank=True)),
                ('supervisor_type', models.CharField(choices=[('supervisor', 'Supervisor/Faculty Advisor'), ('co_supervisor', 'Co-supervisor')], default='co_supervisor', max_length=264)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_supervisor', to='mechweb.student')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
