# Generated by Django 3.1.2 on 2021-02-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0134_customsupervisor_student_studentbatch_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel_address',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='student',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
