# Generated by Django 3.1.2 on 2021-02-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0135_auto_20210301_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
