# Generated by Django 3.1.2 on 2021-09-13 20:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mechweb.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('mechweb', '0135_auto_20210731_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutesOfMeetingCategory',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MinutesOfMeetingsHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='YearlyMinutesOfMeeting',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1994), mechweb.models.max_value_current_year])),
                ('show_only_yearly', models.BooleanField(default=False, verbose_name='Show only yearly MoM')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='File')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MonthlyMinutesOfMeeting',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('month', models.CharField(choices=[('0', 'January'), ('1', 'February'), ('2', 'March'), ('3', 'April'), ('4', 'May'), ('5', 'June'), ('6', 'July'), ('7', 'August'), ('8', 'September'), ('9', 'October'), ('10', 'November'), ('11', 'December')], max_length=264, verbose_name='Month')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='File')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
