# Generated by Django 3.1.2 on 2021-03-12 14:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0136_student_linkedin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentbatch',
            options={'ordering': ['-title'], 'verbose_name': 'Student Batch', 'verbose_name_plural': 'Student Batches'},
        ),
        migrations.CreateModel(
            name='ProgramTestimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('testimonal', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='mechweb.program')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramSpecializationTestimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('testimonal', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='mechweb.programspecialization')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
