# Generated by Django 3.1.2 on 2021-09-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('mechweb', '0136_minutesofmeetingcategory_minutesofmeetingshomepage_monthlyminutesofmeeting_yearlyminutesofmeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyminutesofmeeting',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='File'),
        ),
    ]
