# Generated by Django 3.1.2 on 2021-03-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0137_auto_20210312_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programspecializationtestimonials',
            old_name='testimonal',
            new_name='testimonial',
        ),
        migrations.RenameField(
            model_name='programtestimonials',
            old_name='testimonal',
            new_name='testimonial',
        ),
    ]
