# Generated by Django 3.1.2 on 2021-03-13 14:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0138_auto_20210312_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
