# Generated by Django 3.1.2 on 2021-12-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0139_auto_20211218_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultypage',
            name='designation',
            field=models.CharField(choices=[('0', 'HAG'), ('1', 'Professor'), ('3', 'Associate Professor'), ('2', 'Assistant Professor'), ('4', 'Visiting Professor'), ('5', 'Honorary Professor')], default='3', max_length=2),
        ),
    ]
