# Generated by Django 3.1.2 on 2021-03-13 16:32

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0141_auto_20210313_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='programspecialization',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
