# Generated by Django 3.1.2 on 2021-03-17 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0142_programspecialization_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academics',
            options={'verbose_name': 'Academics', 'verbose_name_plural': 'Academics'},
        ),
        migrations.AddField(
            model_name='student',
            name='webmail',
            field=models.EmailField(max_length=254, null=True, verbose_name='Webmail(Only if User is blank)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User(only if the user exists)'),
        ),
    ]
