# Generated by Django 3.1.2 on 2021-03-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0143_auto_20210317_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='webmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
