# Generated by Django 3.1.2 on 2021-03-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0144_auto_20210317_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefaculty',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='coursefaculty',
            name='session',
        ),
        migrations.AddField(
            model_name='coursefaculty',
            name='current',
            field=models.BooleanField(default=True, verbose_name='Current Instructor?'),
        ),
    ]
